### ISSUE TITLE
UI Content Review

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/mbc-user-subscriptions#19]
Pages that need UI / content review:
- http://localhost:3000 (No targetEmil or key supplied - the case where someone tries to access the URL without using the parameters supplied in the "Unsubscribe" link at the bottom of Message Broker generated email.
![image](https://cloud.githubusercontent.com/assets/2119264/6359738/3520c072-bc43-11e4-92b7-08b206637cb4.png)
- http://localhost:3000/?targetEmail=dlee@dosomething.org (targetEmail, missing key)
![image](https://cloud.githubusercontent.com/assets/2119264/6360810/105866e8-bc4b-11e4-8a8d-769363d43598.png)
- http://localhost:3000/?targetEmail=dlee@dosomething.org&key=12345 (targetEmail, invalid key)
![image](https://cloud.githubusercontent.com/assets/2119264/6360846/4ef63d58-bc4b-11e4-920f-9411f74f1a91.png)
- http://localhost:3000/?targetEmail=dlee@dosomething.org&key=03ae845f34665a4d783786f6ece7f175 (valid email, valid key - UI to adjust subscriptions)
![image](https://cloud.githubusercontent.com/assets/2119264/6360877/8acb4742-bc4b-11e4-87ac-9d7b9c1ef8b2.png)
- http://localhost:3000/thank-you (Success updating user subscription settings)
![image](https://cloud.githubusercontent.com/assets/2119264/6360910/b9f754e8-bc4b-11e4-9a0d-d63ecfc78cd4.png)
-  http://localhost:3000/bla-bla (invalid URL - 404)
![image](https://cloud.githubusercontent.com/assets/2119264/6360924/e0f3ca36-bc4b-11e4-998f-6d8a039594cc.png)

**Comment by barryclark** [comment]
- Remove the user events bullet
- For top two images and the 404 page use the error message: "Error: Page not found. Email help@dosomething.org and we can help resolve your problem."
- Bump up email token expiration to 30 days.
- For the case where the token is too old, use the error message: "This message is too old to unsubscribe from. You can unsubscribe from a more recent email, or send us a message to help@dosomething.org and we'll help resolve your problem."
