### ISSUE TITLE
User Unsubscribe Fender Review

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/mbc-user-subscriptions#7]
The web page accessed by users selecting the "Unsubscribe" link takes the user to a web page where they can adjust their subscription settings. Currently the page is very rough based on a quick copy of the css from the live DS front page:
![image](https://cloud.githubusercontent.com/assets/2119264/6157454/70715832-b20f-11e4-80c8-118957731943.png)

The web page needs to be reviewed for:
- responsiveness
- on DS brand

- Needs to follow **DoSomething.org Style Guide**: http://neue.dosomething.org

The screenshot will be updated as the project progresses.

**Related**:
https://github.com/DoSomething/mbc-user-subscriptions/issues/2

**Comment by barryclark** [comment]
@DeeZone Joe's going to help out with this one :octopus:

**Comment by DeeZone** [comment]
@deadlybutter Hey Joe, lets have a quick chat to see how I can best provide you with something that you can make responsive. As you can see from the screenshot the current state is a mess.

**Comment by deadlybutter** [comment]
I got you @DeeZone 

I'll be able to focus on it Tuesday I think? I'm all full days next week (no school) so whatever time works best for you

**Comment by DeeZone** [comment]
@deadlybutter Sweet! I should have a barebones page for you to work from at that point.

**Comment by deadlybutter** [comment]
Hows this so far? 

![screen shot 2015-02-17 at 1 47 27 pm](https://cloud.githubusercontent.com/assets/897368/6234824/b6f7c246-b6ab-11e4-9be6-505eaf725303.png)
![screen shot 2015-02-17 at 1 47 44 pm](https://cloud.githubusercontent.com/assets/897368/6234825/b6f7fc7a-b6ab-11e4-977d-58e6d9230c64.png)


Need to change the nav links to point to dosomething.org/<stuff> and just run through everything to make sure it's good to go.

**Comment by deadlybutter** [comment]
Quick review with Barry, did some minor changes,

![screen shot 2015-02-17 at 1 55 22 pm](https://cloud.githubusercontent.com/assets/897368/6234943/a5a900bc-b6ac-11e4-96e1-9fb1ba1d3579.png)

The copy for the checkboxes needs updating to be more user friendly

**Comment by deadlybutter** [comment]
Crap, accidentally committed the neue release zip -- ill nuke that from the repo

Also, does this need a footer?

**Comment by DeeZone** [comment]
@deadlybutter Any thoughts on getting the assets out of this PR? Otherwise it looks fantastic!

**Comment by DeeZone** [comment]
- Update Your Email Preferences 
- (MailChimp) The Weekly Do: Our weekly newsletter about campaigns you can take action on 
- (Digest) Your Campaign Digest: Your weekly update on campaigns you signed up for 

For banned emails: 
Oops! Looks like we don't have your email in our system. Email us at help@dosomething.org and we'll get you signed back up.

**Comment by barryclark** [comment]
@deadlybutter Copy updates for the unsubscribe form above ^^ let me know if you have any questions :)
