### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/mbc-user-subscriptions#9]
Update `README.txt` with installation instructions. Currently a the page rendered at "/" is missing all of the assets.

![image](https://cloud.githubusercontent.com/assets/2119264/6261110/f355f700-b7b7-11e4-97dc-22db48c31b56.png)

**Comment by deadlybutter** [comment]
@DeeZone npm install should do everything, ill bring down a fresh repo and see if it works

**Comment by deadlybutter** [comment]
apparently the postinstall doesn't work - Ill just update the readme
